# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca276d500d474908ab71dc0982ad6be51a0ddcb66dbc548c2c142abed696652998eb0876011a22e9c1dcc5977bc7ce0e6d391e06b11975498b0ab7a35a89d5a9

test:
  secret_key_base: 962cd75d2a8c293157142fa970f57476275c4c8db5b27a0367a839ca3793678db6b70ed583dc68fa66e5a4df43b569728bba4abc3d21b1474162d0797760dda5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
